export const AVATARS = [
  { id: "182b03e8", name: "Kevin",    image: "/avatars/kevin.jpg" },
  { id: "21ef04ad", name: "Jessica",  image: "/avatars/jessica.jpeg" },
  { id: "17de03e4", name: "Cathy",    image: "/avatars/cathy.jpg" },
  { id: "1928040f", name: "Sofia",    image: "/avatars/sofia.jpeg" },
  { id: "c5b563de", name: "Lucy",     image: "/avatars/lucy.jpg" },
  { id: "178303d3", name: "Kiara",    image: "/avatars/kiara.jpg" },
  { id: "05a001fc", name: "Jason",    image: "/avatars/jason.jpg" },
  { id: "be5b2ce0", name: "Sameer",   image: "/avatars/sameer.jpeg" },
  { id: "0de70332", name: "Jennifer", image: "/avatars/jennifer.jpg" },
  { id: "03ae0187", name: "Mike",     image: "/avatars/mike.jpg" },
  { id: "1fa504ff", name: "Johnny",   image: "/avatars/johnny.jpg" },
  { id: "7d881c1b", name: "Priya",    image: "/avatars/priya.jpg" },
  { id: "178803d6", name: "Chloe",    image: "/avatars/chole.jpeg" },
  { id: "1a640442", name: "Lisa",     image: "/avatars/lisa.png" },
  { id: "0f160301", name: "Aman",     image: "/avatars/aman.jpg" },
  { id: "057501e8", name: "Allie",    image: "/avatars/allie.jpg" },
  { id: "05b401f3", name: "Misha",    image: "/avatars/misha.jpg" },
  { id: "13550375", name: "Alex",     image: "/avatars/alex.png" },
  { id: "48d778c9", name: "Amir",     image: "/avatars/amir.jpg" },
];
